
all: fsm_gof fsm_extern_state_var fsm_guards

fsm_gof:
	g++ fsm_gof.cpp -o fsm_gof

fsm_extern_state_var:
	g++ fsm_extern_state_var.cpp -o fsm_extern_state_var

fsm_guards:
	g++ fsm_guards.cpp -o fsm_guards

clean:
	rm fsm_gof fsm_extern_state_var fsm_guards
